- innovation.action.php
- innovation.css
- innovation.game.php
- innovation.js
- innovation.scss
- innovation.view.php
- innovation_innovation.tpl
NOTE: I didn't spend any time working out sensible calculations for the division of the forecast and score zone. Ideally, we'd leave one card's width of space between the two area so that it's never unclear whether a card is in the forecast or the score pile. I'll leave this to @lordmcfuzz to address sometime in the future, but it's not urgent now.
> Add forecast zone and foreshadow debug button (#356)

- innovation.game.php
Tested by calling this:
```
self::executeDraw(0, 1, 'achievements', /*$bottom_to=*/ false, /*type=*/ 0, /*bottom_from=*/ true);
```
> Add ability to transfer cards from bottom of deck to available achievements (fixes #420)

- composer.json
- composer.lock
Pins the composer.json file to PHP 7.4 so that we only use PHP 7.4 compatible libraries.
This will have to effect on the actual BGA game - it only deals with test dependencies.
> Update composer lock to PHP 7.4

- .gitignore
- README.md
- composer.json
- composer.lock
- innovation.game.php
- modules/Innovation/GameState.php
- modules/Innovation/Utils/Arrays.php
- tests/Helpers/Mocks.php
- tests/Unit/GameInfosTest.php
- tests/Unit/GameTest.php
- tests/Unit/Innovation/GameStateTest.php
- tests/Unit/Innovation/Utils/ArraysTest.php
- tests/bootstrap.php
* Adds a utility class for accessing game state, rather than using static methods (which are generally difficult to test). This allows this class to eventually be mockable and injectable (passed into a constructor).
* Adds an "arrays" utility class for various encoding/manipulation of array data
* Upgrades PHPUnit to 8, which adds better mocking functionality.
This progresses toward paring down the size of the main game class, which is huge and hard to manage. It allows this codebase to take a more SRP ([Single Responsibility Principle](https://en.wikipedia.org/wiki/Single-responsibility_principle)) approach toward modeling, which will enable easier and more assured refactoring with less risk of bugs.
Note I didn't replace _all_ instances of the static methods around sate in the …
> Add GameState class for easy and testable access of game state

- innovation.game.php
I've gone through all callsites of loadPlayersBasicInfos and removed the ones where we technically want to ignore eliminated players. 
I've manually tested all of the affected cards:  Clothing, Construction, Self Service, A. I., Maastricht Treaty, Socialism, and Specialization.
> Clean up usage of loadPlayersBasicInfos (#457)

- innovation.js
What do you think of this feature? It should also make it more obvious which artifact will go on display since it's easier to tell which ages are skipped.
> Make expansion decks transparent if their base deck is empty (#451)

- innovation.game.php
- modules/Innovation/GameState.php
- tests/Unit/Innovation/GameStateTest.php
This was requested in https://boardgamearena.com/bug?id=10323.
> Add no effect warnings to Societies

- innovation.js
The default delay for tooltips is a bit too slow. This makes it take a lot of time to read all of your cards. By making the tooltips faster, we can give our users a better experience!
> Remove delay from tooltips, making them feel more responsive

- innovation.game.php
I know the no effect detection is a bit more complicated on this card, but players have been asking for a warning for this card in particular: https://boardgamearena.com/bug?id=10327.
I've manually tested a bunch of cases.
> Add warning when Construction will have no effect

- innovation.game.php
This card wasn't possible to fully automate using a general approach, so I needed to add card-specific automation to it.
I manually tested cases with 0, 1, 2, 3, and 4 cards in hand to make sure everything was working correctly.
Also, due to the nature of this change, it won't break any ongoing games when this is deployed.
> Automate Explosives if there are 3 cards or less in hand

- innovation.game.php
I tested it on Construction (where passing is allowed) and Optics (where passing is not allowed).
> Do not automate player choice if passing is an option

- innovation.js
This fixes the bug which prevented tooltips from being re-added to the card names in the game log after refreshing the page.
> Fix bug preventing tooltips from appearing in game log after reload (#441)

- innovation.game.php
One of Delft Pocket Telescope's interactions needs to have automation disabled, otherwise it will reveal hidden information. Opponents shouldn't know that they only have one choosable card when revealing a card from their hand.
> Fix bug in Delft Pocket Telescope causing hidden info to be revealed

- innovation.game.php
To use this option just add `'card_ids_are_in_auxiliary_array' => true` to the interaction (and make sure you use self::setAuxiliaryArray beforehand).
> Add card_ids_are_in_auxiliary_array option to interactions (#514)

- innovation.game.php
- innovation.js
One of the biggest requests from players is to improve the UX with Tools (https://boardgamearena.com/bug?id=18164). this is my proposal for addressing it.
Please note that I structured the JS code in a way that it will make it easy to add confirmation buttons on a timer like we do for meld/dogma actions. I can easily see us wanting to give players an option to confirm card selections as well.
> Add custom warning to Tools

- innovation.game.php
Players will now get a warning (with confirm button) if they try to execute these cards when they won't have an effect.
I manually tested all 3 of these to ensure that it works as intended.
> Add no-op checking to 3 more cards

- innovation.css
- innovation.js
- innovation.scss
I opted for a simpler look than what's on the real cards (this leaves more room for the text, and saves us from adding more images to the game, especially since many people dislike the checkerboard pattern to begin with).
It looks good on both the first and third edition card backgrounds:
> Stylize echo effects (#355)

- innovation.game.php
- material.inc.php
This makes things consistent with the changes we made regarding special achievement timing in the base and artifact special achievements.
> Remove 'immediately' from Echo special achievements

- innovation.css
- innovation.scss
> Remove transparency from current effect highlighting (#614)

- innovation.game.php
If a card needs to be returned to a unique supply pile (determined by age/type or whether it is a relic), then this will automatically choose the card.
I also made the order of other automated cards deterministic (e.g. if you play Oars, it will take cards from the left side of their hand and work over to the right side, instead of taking them from random spots each time.
> Automatically return cards when the order doesn't matter

- innovation.game.php
A stale card reference can cause really subtle bugs. By refetching the card inside transferCardFromTo, we eliminate the need to fix potential bugs at each call site.
> Add general failsafe to transferCardFromTo to refresh card state

- innovation.game.php
Cards are drawn to hand by default so we don't need to specify the location explicitly.
> Stop passing 'hand' explicitly to executeDraw

- innovation.game.php
The majority of interactions are forced, not optional. By setting the default to false, we only need to specify `can_pass` when it needs to be set to true.
This helps reduce the size of our main PHP file, which is currently way too long (it's beginning to take too long to upload to BGA).
> Make can_pass default to false

- innovation.game.php
With the release of Echoes (release_version=2) we will no longer need the icon hashes for Complex Numbers, so we can remove this from the table creation.
This change won't break ongoing games.
> Stop calculating icon hashes during table creation (#685)

- innovation.game.php
- material.inc.php
I also had to disable automation for certain cards since the selection order again matters for the purposes of special achievement eligibility. Fortunately, we are not disabling that much automation so this isn't a big deal.
> Add special achievement check after every transfer (#753, #764)

- innovation.game.php
This is helpful during testing because it means we don't have to restart the game when trying to test a particular card and it happens to be used as an achievement.
> Make it possible to use the debug buttons when a card is used as an achievement

- innovation.game.php
This provides more consistency to how we decide when to automate cards.
I've chosen to do special achievement checks after every card transfer (or splay). Card transfers will be automated as much as possible, except if the cards are being returned (since the order affects the position that they end up in decks) or if they are being melded. In either of these cases, since we can't automate the entire sequence of transfers, we choose to give players control over the entire selection order for consistency.
I think the above gives us the best balance between automation and giving players control over the order (even though being clever about the selection order was never the intent of the game designer/publisher).
> Re-add automation to when cards are being moved to the score pile

- innovation.game.php
I recently added enable_autoselection=false to a bunch of cards in light of the recent special achievement check changes. However, I had to revisit that since we should still be able to autoselect if there's only one possible option (we just don't want to meld or return cards if the selection size is at least 2).
> Automate single card returns and single card melds (#777)

- innovation.js
This was requested in //boardgamearena.com/bug?id=76960.
> Make it more obvious when an Echoes card is going to be drawn

- innovation.game.php
After second thought, we should keep this automation here after all. It's more consistent with how we are handling other cards (if we can move all of the cards to the score pile automatically, then we do so, but if we are returning to the deck, then we give players a choice).
> Uncommment Mobility automation (#735)

- innovation.game.php
This bug only occurred when the page was being refreshed (we already had similar code in place for updating the current effect when the page wasn't being refreshed).
> Highlight correct Echo effect after page refresh (#759)

- innovation.css
- innovation.js
- innovation.scss
We used to use a red color to signify the "selected" card during the initial phase of the game. I switched that to black, and used red to highlight cards when any player is prompted to click on a card mid-dogma. This should provide a helpful distinction between when players are clicking on a card for the purposes of melding/dogma/etc. vs clicking on a card as a result of on ongoing dogma action (regardless of who initiated it).
> Add visual distinction when mid-dogma (#746)

- dbmodel.sql
- innovation.js
- material.inc.php
This new order is more intuitive because it's sorted by the age of the "May also be claimed via X" alternate condition.
While updating this I also found a typo. We were claiming that Translation was an age 5 card, but it's actually an age 3 card.
> Re-order special achievements

- innovation.js
The splay tooltip wasn't looking for bonuses underneath the other piles (the ones not about to be splayed).
Also, while I was here, I knocked out a few TODOs for Cities.
> Add score calculation to meld tooltip and fix bug in splay tooltip (#791)

- gameinfos.inc.php
Testing this change together with https://github.com/micahstairs/bga-innovation/pull/808, I got the following screenshots:
Relevant bug reports:
- https://boardgamearena.com/bug?id=67958: There is a second and third place awarded when there should only be one winner and the rest losers
- https://boardgamearena.com/bug?id=28575: In a round-robin tournament when END OF GAME BY SCORE, the score difference is messed up
- https://boardgamearena.com/bug?id=76351; lost ELO for 'tying' against my teammate in team game
> Remove tie_breaker_description and set losers_not_ranked

- innovation.js
- innovation.view.php
In addition to fixing the 1,2,1,2... bug on mobile, this also fixes a bug I just noticed where we still rendered the text "Forecast (view cards)" even when the Echoes expansion was not in play!!
> Fix forecast and score pile layouts (#422)

- innovation.css
- innovation.scss
It personally feels a lot better when I click on them now. It's more obvious to me that the card I clicked on is actually selected.
> Highlight selected card white instead of black

- innovation.js
I checked and cards only end up in the forecast via a "draw and foreshadow" mechanism, so it's not possible for Artifacts to end up in the forecast anyway.
> Remove TODO (#685)

- gameinfos.inc.php
- innovation.action.php
- innovation.css
- innovation.game.php
- innovation.js
- innovation.scss
- Reverted changes to how gold/silver stars are awarded at the end of the game
- Added a "Browse all cards" button which allows players to look through all the cards in use for that game
- Fixed a bug which occurred when the Echo effect was skipped (due to chained execution via cards like Satellites) on certain cards (e.g. Karaoke)
- Made it more obvious which card was selected when using Scissors
- Added card revealing to Typewriter in order to prove which colors were returned
> Push latest changes to the alpha 

- innovation.game.php
Without this change, Code of Laws will reveal hidden info if a player can't tuck cards.
> Fix automation bug affecting cards like Code of Laws

- innovation.game.php
https://boardgamearena.com/bug?id=77811
Basically, we were resetting the aux value after the echo effect in all situations (as opposed to only resetting it after executing a *buried* echo effect).
> Fix bug affecting cards like Jet

- innovation.css
- innovation.game.php
- innovation.js
- innovation.scss
I also made it so that when the "dogma confirmation" personal preference is on, that the timer confirmation button is separate from the warning confirmation button. This helps solve the problem where players will click confirm our of habit, not realizing that it was a warning instead of just a countdown timer.
I also added the card's age to the warning message for consistency with how we render card names elsewhere in the game.
I also made a couple of backend changes, to make the code a bit more clearer around echo and non-demand effects (originally I thought that an echo effect was a non-demand effect, but I've since learned that that's not true).
> Add warning when a dogma action will end up sharing the non-demand or echo effect with another player

- innovation.css
- innovation.js
- innovation.scss
- material.inc.php
Instead of adding in new brown images like we see on the real cards, I just decided to use a grayscale version of one of the colored icons. It does the trick!
This closes #384.
> Render special icons on Cities special achievements (#384)

- innovation.js
Before this change, there was a bug where if you clicked "Cancel" during the endorse prompts and then tried melding a card that was tuckable, it would proceed with the endorsed action instead of doing a meld.
> Fix stale click handlers when cancelling endorse

- innovation.game.php
This card now behaves correctly if a yellow card is melded after a blue card.
> Fix endorsement of Stethoscope (#632)

- innovation.game.php
This was reported in https://boardgamearena.com/bug?id=78628.
Basically what was happening was that the transfer of the fountain card was triggering updateFlagsAndFountains again (before the first one even finished), causing too many fountain cards being awarded, and then revoking the extra afterwards.
> Fix bug which happened when gaining/losing two fountains

- gameinfos.inc.php
I accidentally reverted this change while undoing the change to the gold/silver stars. One of our BGA players pointed out that this change was never actually made (despite the fact that we told everyone we made the change).
> Stop ranking losers

- innovation.game.php
When Dancing Girl is endorsed, it can visit the same boards more than once. So instead of counting the number of times that the Dancing Girl has moved, I needed to count the number of unique boards it visited instead.
> Fix endorsement of Dancing Girl (#632)

- dbmodel.sql
- innovation.game.php
It wasn't possible to use existing auxiliary variables since those are all scoped to a specific execution of a card, and this needs to be scoped to the entire action. It wasn't possible (without very complicated encoding) to use a global variable since each player needs its own counters. So the simplest solution here is to add a column to the player table to keep track of this counter (resetting it to 0 at the end of each action).
I tested this by endorsing Democracy, but this should always work fine in the very unlikely case that the card gets executed twice due to nested execution in the same action.
> Fix endorsement of Democracy (#632)

- innovation.js
I went through our JS file and fixed all of the translations I believe.
Here's an example of one of the strings this fixes. FYI I was able to test this using the following feature in the studio: 
Before:
After:
> Fix JavaScript translations (https://boardgamearena.com/bug?id=79259)

- innovation.game.php
- innovation.js
The only wrinkle was that I had to hide the "/X" part if the game ends by score or dogma. Otherwise this would have been a 1-line change.
> Make it obvious in the player panel how many achievements are required to win

- gameoptions.inc.php
- innovation.css
- innovation.js
- innovation.scss
- innovation_innovation.tpl
- misc/_mixins.scss
- misc/_variables.scss
Players can now choose whether to put the decks and achievements on the right side or on the bottom (the default is to automatically pick based on screen size).
Before (mobile):
After (mobile):
> Make the layout responsive and configurable

- innovation.js
> Fix mobile layout issue when decks/achievements are on right

- innovation.js
I tried a bunch of things to make the number of cards per row smarter but it turned out that simply setting it to 3 worked best on all of the devices I tried it on.
Let's give this a whirl in the alpha!
> Fix layout issues with score/forecast popup (#929)

- innovation.game.php
- innovation.js
The forecast popup is now opened automatically if a player is being prompted to select cards from their forecast (https://boardgamearena.com/bug?id=80776).
This mirrors what is done for the score pile already.
> Open forecast popup when player is prompted to select forecast cards

- innovation.game.php
- innovation.js
This required a major refactoring which split the no-op detection into per-player and per-effect-type queries. The result is that it actually simplifies the logic to check whether cards have an effect (meaning we need to write less special cases for specific cards, since we can group them together more easily).
This change also adds some extra no-op detection to several cards that we didn't have before.
While I did some testing, there's a high chance of introducing bugs, so we definitely want to let this soak in the alpha for a few extra weeks.
> Do not show sharing warning if share has no effect

- innovation.game.php
When `location_to = "none"`, that means that the player is just choosing a card and it's not actually being moved everywhere. So all of these cases should be handled by getTransferInfoWithOnePlayerInvolved (not getTransferInfoWithTwoPlayersInvolved), otherwise an error gets thrown (this error only actually surfaces in certain situations when the effect is shared - it's the result of a stale `owner_to` value).
> Fix bug when location_to=none (https://boardgamearena.com/bug?id=81808)

- innovation.css
- innovation.scss
Ignore the other diffs. I just installed SASS on a new computer and it seemed to want the color codes in RGB instead of using constants.
> Fix size of City titles on .L cards (#945)

- innovation.js
From @ultimatefiend: "Hmm interesting. I clicked to not endorse and then I clicked on the card before my confirmation timer ran out and then it tucked it"
> Disable tuck clicking after pressing 'Dogma without endorse'
