dbmodel.sql, innovation.game.php
=> Implement "Chronicle of Zuo" card

dbmodel.sql, innovation.game.php
#82 - Using the ID to detect whether its an artifact card or not.  It would be better if that came from the database.
=> Ark of the Covenant

innovation.action.php, innovation.game.php, innovation.js
For issue #35 , to add debug buttons. 
The "return this card" button doesn't do anything yet and I haven't really had the chance to test much, but this is where I'm at so far.
=> Debug buttons

dbmodel.sql, innovation.game.php
Completed except for the green case (unsplay all piles), I'm a bit stuck here. 
Going to post in the discord as well, but my current method gets the error 
```
Server syntax error:
Notice: Undefined variable: location_from in /var/tournoi/release/games/innovationnormaljosh/999999-9999/innovationnormaljosh.game.php on line 5627
{"status":1,"data":{"valid":1,"data":null}}
```
I'm thinking something's going wonky with the code around lines 4003, where $rewritten options isn't setting a value for location_from, but to be honest I'm not entirely clear on what's happening around that code. It seems like the "else" should be triggered since I have a splay_direction key in my options array, but for some reason it isn't. 
Green case that isn't working: 
``` php
// "If green, unsplay all piles" …
```
=> Normaljosh necronomicon

dbmodel.sql, innovation.game.php, material.inc.php
Adding age 4 artifact cards Moses and Petition of Right
=> Normaljosh petition

innovation.game.php
… order of events when digging for an artifact.  First, you draw up in age and then you look to see if any artifacts remain.
=> Kahlia fix dig event with proper drawing mechanic

dbmodel.sql, innovation.game.php
Added a new function that counts visible cards.
Otherwise, the cards are pretty straightforward
=> Kahlia age7 - corvette, jedlik, singer

dbmodel.sql, innovation.game.php
-random fix for hunter-lenox
-4 age 9 cards
=> Kahlia Age 9 artifacts - syncom, phillips, marilyn, and luna

innovation.game.php
This was supposed to be part of #135 but I forgot to upload it before merging
=> Simplify card implementations for #135

dbmodel.sql, innovation.game.php
-kilo,puffing,us decl, stamp act
-added function to count symbols in a pile (will be useful for heritage and supremacy later)
=> #135 - age 6 - kilo, puffing, us decl, stamp act

dbmodel.sql, innovation.game.php
the card Magnavox Odyssey is added
=> Age 9 Artifact Magnavox Odyssey

dbmodel.sql, innovation.game.php
Battleship Bismarck implementation
=> Age 8: Battleship Bismarck

innovation.game.php, material.inc.php
this also fixes complex number's demand.  It is now a non-demand.
=> #184 - newton wickins relic

dbmodel.sql, innovation.css, innovation.game.php, innovation.js
Also put the cards in hands and score piles in the correct order (sorted by age, then type, then by is_relic).
=> Use relic images on back of cards (#180)

innovation.game.php
make the reveal automatic rather than an interaction (removing a TODO)
=> Cross of Coronado - remove TODO 

innovation.css, misc/css_generator.py, misc/to_be_appended_into_innovation.css
I'm fairly sure this works but is currently untested as relics may be bugged.
=> INNO-241: Setting hex icon classes for relics

innovation.css, innovation.js
=> Inno 195: fixing ages numbers in special achievements tool tips.

dbmodel.sql, innovation.css, innovation.game.php, innovation.js
Also updated some comments, but I didn't update any variable naming. We can do that incrementally over time when we touch code.
=> Update user-visible wording from 'pile' to 'stack' (#273)

innovation.game.php
=> #282, #281, #277, #276, #265

innovation.game.php, stats.inc.php
This is still missing logic for the demand/compel statistics.
I'm not sure where they go.  Presumably they would end up in the nested execution logic?
=> #202 - stats

README.md, innovation.css, innovation.js, innovation.scss, misc/_variables.scss
=> Inno 321 fix achievement width

innovation.css, innovation.js, innovation.scss
Also fixed some color issues with the tooltip icon counts
=> INNO-386 + 380: icon and title updates

gameoptions.inc.php, innovation.game.php
Fixed some TODOs for Cities
Added game options for Echoes and Cities
=> Cities - onmeld

dbmodel.sql, innovation.css, innovation.game.php, innovation.js, innovation.scss, material.inc.php
This is kind of a mish mash of different features.
=> Kahlia cities echoes basics + noodles, puppet, dice, comb

.gitignore, README.md, modules/Innovation/Utils/Strings.php, tests/Unit/Innovation/Utils/StringsTest.php
* Improve alphanumeric card name checks to handle case insensitivity and punctuation
* Adds .gitignore (and sftp) entry for ignoring phpunit's result cache file
=> Improve alphanumeric card name checks to handle case insensitivity and punctuation

innovation.game.php, innovation.js
It defaults to however many cards you currently have of that color. I display 6 options since that allows them to pick X ... X+5 (since Mona Lisa draws 5 cards). If you click the arrows it will change the selection of numbers that you have. In practice, users will never need to click these button, but this gives them the flexibility to pick different numbers if they really want to.
=> Add non-negative integer selection to Mona Lisa (#225)

dbmodel.sql, innovation.css, innovation.game.php, innovation.js, innovation.scss
There's still some outstanding TODOs, but I've done some basic testing and this should greatly help while implementing the cards.
=> Implement basic echo effect functionality (#359, #355)

innovation.action.php, innovation.game.php, innovation.js
This will be particularly useful for testing echo effects.
=> Add tuck debug button

innovation.js
=> Add tooltip to relic regardless of location (#463)

innovation.css, innovation.js, innovation.scss
Before:
After (font sizes 4-7):
Before:
After (font sizes 4-7):
I also fixed a bug which made it so that createAdjustedContent never used the max font size (it subtracted one from the font *after* finding the ideal size). This means that we were always rendering the font smaller than it needed to be.
=> Improve layout of age squares within dogma text on .M cards (#245) 

innovation.css, innovation.js, innovation.scss
This was requested in https://boardgamearena.com/bug?id=66491.
=> Make it possible for players to tell which type each card is

gameoptions.inc.php, innovation.css, innovation.js, innovation.scss
=> Add game preference to use simplified graphics (#494)

innovation.js
I was able to replicate this bug reliably when the last card of a deck was going to a player's own score pile.
=> Fix bug which sometimes resulted in wrong deck opacities

innovation.css, innovation.game.php, innovation.js, innovation.scss, material.inc.php
This simplifies some of the code and will also make some of the log messages clearer when there are more than one achievement with the same age.
=> Remove achievement_name field from materials file

innovation.game.php
also remove empty detections for glory and victory
=> #490 - fix count function

innovation.css, innovation.scss
See https://github.com/micahstairs/bga-innovation/blob/main/innovation.css for the CSS file we had in production prior to the Artifacts release.
=> Revert font to original font before Artifacts release

innovation.game.php
=> Make it more obvious when player only has one action

innovation.game.php
I tested this on Optics in both a 2-player and 3-player game and it works like a charm!
=> Automate player choice when there's only one option (#556)

innovation.game.php
I tested that this extended automation works on Construction, The Pirate Code, and Combustion.
I also tested that this doesn't get triggered on Baghdad Battery (since the melding order matters) and Tools (since the return order matters). We could theoretically extend this even more in the future since the melding order doesn't matter if the colors are different and the return order only matters if two cards are being returned to the same supply pile. However, those are out of scope for now.
=> Extend automation from a single card to multiple cards when order doesn't matter

innovation.game.php
This bug has been reported by players: https://boardgamearena.com/bug?id=68584.
=> Fix bug preventing some text from being translated in the command bar

innovation.game.php
=> Add option to prompt player to pick an icon type (#510)

innovation.css, innovation.scss
=> Add hex icons to City cards (#375)

innovation.css, innovation.scss
=> Render Echo hex icons

innovation.game.php
=> Add proper revealing to Shroud of Turin (#540)

innovation.game.php, innovation.js
Also finished implementing Plumbing as a proof of concept.
Closes #497.
=> Allow cards to be selected from the bottom of a pile (#497)

innovation.game.php, innovation.js
This is consistent with how we currently highlight for other dogma effects.
=> Highlight echo effect when being executed

dbmodel.sql, innovation.game.php, innovation.js
=> During nested execution, execute the top card's echo effect

innovation.game.php
=> Add tooltips to Rock's log messages

innovation.game.php
=> Update Elevator's logging

innovation.css, innovation.js, innovation.scss
=> Add blank hex icon to tooltip and .M card (#360)

innovation.css, innovation.js, innovation.scss
=> Add music note to Saxophone .M card (#360)

innovation.game.php
See #665 for context on why we are making this change (we got a clarification from Chris).
=> Reveal entire hand instead of only cards which might have a bonus (#665)

material.inc.php
Now the dogma effects in the materials file are ordered in the same order that they are executed.
=> Move echo effect to beginning of entries in materials file

dbmodel.sql, innovation.game.php, innovation.js, material.inc.php
barometer updates
tuning fork first attempt
=> fix watermill, etc

innovation.game.php
By the time Echoes is launched, we will be able to assume that there are no remaining games with release_version=0 (right now there's only 1 such game left).
=> Retire dead code branches (#645)

innovation.game.php
Two Echoes cards were using `choose_opponent` even though it was deprecated. I've replaced it with `choose_player`.
=> Remove choose_opponent and choose_opponent_with_fewer_points (#645)

innovation.game.php
This bug had the potential to affect Industrialization as well.
=> Fix bug mainly affecting Fermenting (#688)

innovation.game.php
Also added `executeDrawAndScore` helper method.
=> Add missing score keywords (#594)

innovation.game.php
This is intended to be a no-op
=> Add executeDrawAndMeld helper

innovation.game.php
This is intended to be a no-op
=> Use executeDrawAndForeshadow helper

innovation.game.php
I've been removing these incrementally for some time, so I thought I might as well do a find-and-replace to eliminate them for good.
=> Remove pointless 'see B' comments

innovation.game.php
Complex numbers,tuning fork, human genome
=> #705,#685,#672,#671

innovation.game.php
In addition to fixing the bugs, I cleaned up the affected code a bit.
=> Fix 'can_pass' bugs (#709, #710)

innovation.game.php
=> Fix prompt when selecting subset using card_ids_are_in_auxiliary_array (#722)

innovation.js
=> Fix score and forecast zone layout (#422)

innovation.css, innovation.js, innovation.scss
=> Add alternate deck layout for 2+ expansions in play (#647)

innovation.css, innovation.scss
=> Render .L music note and blank hex icons (#750)

innovation.game.php
I added automation, no effect detection, and logging. The card is now much easier to dogma!
=> Improve UX of Periodic Table (#754, #755)

innovation.game.php
This is based on a clarification from Carl in https://boardgamegeek.com/thread/1620510/article/23440477#23440477.
=> Fix Katana's implementation

innovation.game.php
This was reported in https://boardgamearena.com/bug?id=76440.
=> Handle situation where meld causing the game to end with a winning special achievement

innovation.js
=> Show preview of score after splaying (https://boardgamearena.com/bug?id=76738)

innovation.game.php
Reported in https://boardgamearena.com/bug?id=75931.
=> Fix bug in Marcha Real and add more logging

innovation.js
=> Drop number of score/forecast cards in each row down to 5 (#741)

innovation.css, innovation.js, innovation.scss
This has been a big request from players! https://boardgamearena.com/bug?id=68916
=> Add feature which allows players to browse list of special achievements (#533)

innovation.game.php
Now we will give 1 gold star to the winner(s) and 0 to the losers. I tested this in several games in the studio, but I really want to let this soak in alpha for a while.
Relevant bug reports:
- https://boardgamearena.com/bug?id=67958: There is a second and third place awarded when there should only be one winner and the rest losers
- https://boardgamearena.com/bug?id=28575: In a round-robin tournament when END OF GAME BY SCORE, the score difference is messed up
=> Change how stars are awarded at end of game (#643)

innovation.css, innovation.js, innovation.scss
I also noticed that the special achievements were slightly off-center, so I fixed that at the same time.
=> Add small 'Browse' button near special achievements

innovation.css, innovation.game.php, innovation.js, innovation.scss
=> Show current progression towards each special achievement

innovation.game.php
Without this helper, it gets confusing because game_rules=1 means 3rd edition and game_rules=2 means 1st edition.
=> Use usingFirstEditionRules helper to improve code clarity

innovation.css, innovation.js, innovation.scss
=> Make it possible for players to browse full list of cards (#345)

innovation.css, innovation.game.php, innovation.js, innovation.scss
Make it possible for players to browse full list of cards
=> Push latest changes to alpha

innovation.action.php, innovation.css, innovation.game.php, innovation.js, innovation.scss
I should have implemented this a long, long time ago...
=> Add debug buttons to splay piles

innovation.game.php
=> Add card names to action bar in Scissors

gameinfos.inc.php, innovation.game.php
This was created using the `git revert` command.
=> Revert changes to how gold/silver stars are awarded at the end of the game

innovation.css, innovation.scss
The blue I used was a little too bright and didn't match the back of the Echoes cards very well.
Before:
After:
=> Tweak color of Echoes blue

innovation.js
=> Use colored icons to indicate which set is going to be drawn

innovation.css, innovation.game.php, innovation.scss
=> Add music note icon to game log (#685)

innovation.js
=> Add tooltips to score and forecast at all times (#758)

innovation.game.php, modules/Innovation/GameState.php, tests/Unit/Innovation/GameStateTest.php
Also added a new `usingThirdEditionRules` function to improve code clarity.
=> Fix automation bug in Oars (#646)

innovation.game.php
I also cleaned up some obsolete migration code from past releases.
=> Fix bugs discovered during migration simulations (#648)

innovation.js
=> Add tooltips to cards in card browser

innovation.css, innovation.js, innovation.scss
=> Add search icon to .M cards (#369)

innovation.css, innovation.js, innovation.scss
=> Add an even more condensed layout when 4 sets are in use

innovation.game.php, states.inc.php
This re-uses the existing interaction engine:
=> Add interaction for Search icon (#403)

innovation.game.php
I accidentally pushed https://github.com/micahstairs/bga-innovation/commit/eb3c3af19aa20ce38307cfbf8e053298612a609b and https://github.com/micahstairs/bga-innovation/commit/6bc6b82c139377900e62ffdf9da10608c4b62eb4 without creating a PR, so pretend that those commits are part of this too.
=> Give players temporary achievements for visible fountain and flag icons (#861, #862)

innovation.game.php
=> Fix endorsing cards which have multiple effects (#868, #869)

dbmodel.sql, innovation.js
=> Fix special achievement ordering bug

innovation.game.php
As one player pointed out, the game log isn't intended to explain the rules, it's intended to dictate what happened in the game.
=> Eliminate verbose messages about drawing Cities

innovation.js
=> Add coloring to age squares in meld tooltip

innovation.game.php
This fixes https://boardgamearena.com/bug?id=73998 and https://boardgamearena.com/bug?id=73998.
=> Fix some translations

innovation.js
=> Add tooltips to flag and fountain cards

innovation.game.php
This was reported in https://boardgamearena.com/bug?id=78852 and I checked other cards for similar bugs.
=> Make text in choice buttons translatable

innovation.game.php
I manually tested a bunch of cases:
=> Fix endorsement of Jet (#632)

innovation.game.php
This was reported in https://en.boardgamearena.com/bug?id=78989.
=> Fix error in Colt Paterson Revolver

innovation.game.php
This PR also includes a bit of refactoring (I added the isExecutingAgainDueToEndorsedAction method to make things less error prone). I also added a TODO to address once the other outstanding PRs are merged in.
=> Fix endorsement of Charitable Trust (#632)

innovation.game.php, innovation.js
According to Watno, the same card can be executed twice (which makes sense when I try to read the card as literally as possible).
=> Fix endorsement of Karaoke (#632)

innovation.css, innovation.scss
=> Render card layout for .L cards for Cities (#596)

innovation.js
=> Add missing tooltips to relic in card browser

innovation.css, innovation.game.php, innovation.js, innovation.scss, innovation_innovation.tpl
Instead of coming from nowhere, it now comes from the center of the city card.
=> Make flags/fountains come from a more logical place (#889)

innovation.game.php
=> Fix when Glory and Victory are awarded (#907)

innovation.js
Requested in https://forum.boardgamearena.com/viewtopic.php?t=28777.
=> Make compact view show echo effects

innovation.game.php
Some players were confused by the term topdeck. We might as well use terminology as close as possible to the dogma text anyway.
=> Avoid using topdecking term

innovation.game.php, innovation.js
I also fixed a bug where if we tried to draw a City and there weren't any cards left in the deck, we no longer get an error but gracefully fall back to the base deck (or Echoes deck when applicable).
=> Indicate when a Meld action will cause a City card to be drawn

innovation.game.php
It's quite likely this was causing rare automation bugs, or at least it had the potential to introduce subtle bugs in the future.
=> Fix potential bugs resulting from mishandling special player id values

gameoptions.inc.php, innovation.css, innovation.js, innovation.scss, innovation.view.php, innovation_innovation.tpl
=> Fix layout issues (#914)

innovation.js
=> Fix display bug occuring during spectator mode

innovation.js
=> Shrink piles if too wide

innovation.game.php, stats.inc.php
=> Add statistics for Cities expansion (#521)

innovation.css, innovation.js, innovation.scss, innovation_innovation.tpl
=> Add pile size counters

innovation.game.php
This bug was reported in https://boardgamearena.com/bug?id=79977.
=> Fix Puzzle Cube bug with empty board

innovation.css, innovation.scss
=> Fix layout bug when age 10 deck is empty (https://boardgamearena.com/bug?id=78908)

innovation.game.php, innovation.js
This fixes an error involving Battleship Yamato, and it also fixes a bug when you are melding a new color using a city card.
=> Fix a few bugs in the meld tooltip

innovation.game.php, modules/Innovation/GameState.php, modules/Innovation/Utils/Arrays.php, tests/Unit/GameTest.php, tests/Unit/Innovation/GameStateTest.php, tests/Unit/Innovation/Utils/ArraysTest.php
A while back we add some unit-tested helpers but we never got around to actually using them. This PR takes advantage of those tested helpers and removes the duplicated code.
=> Use refactored helpers

innovation.css, innovation.js, innovation.scss, innovation_innovation.tpl
=> Add forecast card count to player panel

innovation.game.php
Fixed Battleship Bismarck bug which occurred when draw triggers end of game. The code isn't set up to handle any card transfers in stInteractionStep.
=> Fix Battleship Bismarck bug

material.inc.php
Looks like I tried to make this change earlier but it must've gotten dropped in a merge conflict or something.
=> Adjust wording of Moses to improve clarity (https://boardgamearena.com/bug?id=81736)
